version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.restapi.dataconnector
    environment:
      ADDONS: "eea.restapi.dataconnector[test]"
      DEVELOP: "src/eea.restapi.dataconnector"
